name: Nix Format

on:
  pull_request:
    branches-ignore: master
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Detect Nix system
        run: echo "SYSTEM=$(nix eval --raw --expr builtins.currentSystem --impure)" >> "$GITHUB_ENV"

      - name: Check Nix formatting
        run: nix build -L ".#checks.$SYSTEM.treefmt"
